### ISSUE TITLE
Migrating the package to Null safety?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/injectable#170] opened 2021-01-29 19:03 UTC
I use injectable in my app and it is one of the major null safety migration blocker. We had appreciate if you could migrate the package to null safety.

**Comment by britannio** [comment] 2021-02-09 11:23
Duplicate of https://github.com/Milad-Akarie/injectable/issues/147

I use this package in several apps so it's a blocker for migrating these apps to null safety.

**Comment by Milad-Akarie** [comment] 2021-02-27 15:03
@ganeshrvel  nullsafety version was just released 
https://pub.dev/packages/injectable/versions/1.2.0-nullsafety
https://pub.dev/packages/injectable_generator/versions/1.2.0-nullsafety

**Closed by Milad-Akarie** 2021-02-27 15:03 UTC
