### ISSUE TITLE
Injectable: Created file resolves imports incorrectly

### ISSUE THREAD

**Issue by PDDStudio** [Milad-Akarie/injectable#12] opened 2020-02-19 10:28 UTC
Hello,

We've started using injectable in our project.
I've realized that the generated file has some problems with wrong/duplicated imports.

For example, I've my `dio` instance registered via `registerModule` & `lazySingleton`.

```dart
@registerModule
abstract class RegisterModules {

  @lazySingleton
  Dio get dio => Dio();

}
```

After generating the `iconfig.dart` file I can see that there are problems with resolving the correct import of `dio`:

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

<other imports>
import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:dio/src/dio.dart';

void $initGetIt(GetIt g, {String environment}) {
  g.registerLazySingleton<Dio>(() => Dio());
  _registerEagerSingletons(g, environment);
}

// more code
```

I don't know if this issue has been reported yet, but I couldn't find anything similar to this.
For now I'm ending up removing the duplicated (& wrong) import by hand.

**Comment by ResoDev** [comment] 2020-02-20 10:32
This also happens with Firebase. It imports `.../src/something.dart` although 3rd party package imports should never point to the `src` directory directly.

**Comment by Milad-Akarie** [comment] 2020-02-20 10:39
Hey @ResoDev  @PDDStudio, 
Are you sure you're on the latest version 0.2.2?

**Comment by Milad-Akarie** [comment] 2020-02-20 10:41
@PDDStudio You mean two import statements are generated?

**Comment by ResoDev** [comment] 2020-02-20 10:54
@Milad-Akarie yes, just tested it again.
Injectable imports 
```dart
import 'package:firebase_auth/src/firebase_auth.dart';
```
which is actually an error: `The imported library ''package:firebase_auth/src/firebase_auth.dart'' can't have a part-of directive.
Try importing the library that the part is a part of.dart(import_of_non_library)`

Here's the module:
```dart
@registerModule
abstract class FirebaseInjectableModule {
  @singleton
  GoogleSignIn get googleSignIn => GoogleSignIn();
  @singleton
  FirebaseAuth get firebaseAuth => FirebaseAuth.instance;
}
```

**Comment by Milad-Akarie** [comment] 2020-02-20 11:09
@ResoDev  I'm actually working on a better approach to handling custom initializers that will solve all the import issues and more, hopefully it will be done by this weekend so stay tuned.

**Comment by ResoDev** [comment] 2020-02-20 11:13
@Milad-Akarie Thank you. I hope we're going to arrive at a stable-ish version because I'd love to use this package in a tutorial series.

A bit off-topic here, but get_it 4.0.0 shouldn't disrupt the API of this lib, right? Maybe just the implementation.

**Comment by Milad-Akarie** [comment] 2020-02-20 12:03
@ResoDev  I don't think it will, I've already tried it with get_it v4 and everything worked just fine, I'll add support to v4 as soon as it's released or maybe even before.

**Comment by Milad-Akarie** [comment] 2020-02-24 16:43
@PDDStudio @ResoDev  This should be fixed in v0.2.3 check it out!
Thanks for reporting.

**Closed by Milad-Akarie** 2020-02-24 16:43 UTC

**Comment by PDDStudio** [comment] 2020-03-25 10:16
Sorry for the late reply, I totally lost track of this issue. We've updated to `0.3.0` today and this issue is fixed. Thanks!

**Comment by sedobrengocce** [comment] 2020-05-18 23:10
I'm using versio 0.4.0 and the problem is present again


// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

<other imports>
import 'package:http/src/client.dart';
import 'package:get_it/get_it.dart';

void $initGetIt(GetIt g, {String environment}) {
  final injectableModules = _$InjectableModules();
  g.registerLazySingleton<Client>(() => injectableModules.httpClient);
<more generated code

}

class _$InjectableModules extends InjectableModules {}

**Comment by Milad-Akarie** [comment] 2020-05-19 00:54
@sedobrengocce  it's importing from the src not the library? 
could you show me your setup?

**Comment by sedobrengocce** [comment] 2020-05-19 10:00
@Milad-Akarie sure!

import 'package:injectable/injectable.dart';

import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

@module
abstract class InjectableModules {
  @lazySingleton
  http.Client get httpClient => http.Client();

  @lazySingleton
  @preResolve
  Future<SharedPreferences> get sharedPreferences async => await SharedPreferences.getInstance();
}
