### ISSUE TITLE
Firestore is not imported in injection.config.dart

### ISSUE THREAD

**Issue by RabiRoshan** [Milad-Akarie/injectable#77] opened 2020-06-01 03:59 UTC
**This is the injectable module:**
<img width="482" alt="Screenshot 2020-06-01 at 9 21 14 AM" src="https://user-images.githubusercontent.com/19388268/83374586-accc5080-a3e9-11ea-954b-4501dfd2bee5.png">

**This is the generated _injection.config.dart:_**
<img width="658" alt="Screenshot 2020-06-01 at 9 21 50 AM" src="https://user-images.githubusercontent.com/19388268/83374613-c8375b80-a3e9-11ea-83f3-35fa44a3cf51.png">

**This is the vscode suggestion for the actual import:**
<img width="695" alt="Screenshot 2020-06-01 at 9 22 35 AM" src="https://user-images.githubusercontent.com/19388268/83374701-06cd1600-a3ea-11ea-8cae-4eb3d256cbe0.png">

By the way, I am developing for Flutter Web.
Tried with both **injectable 0.3** and **injectable 0.4**

**Comment by Milad-Akarie** [comment] 2020-06-01 20:00
Hey @RabiRoshan I can't reproduce. it generated just fine
<img width="626" alt="Screen Shot 2020-06-01 at 9 59 30 PM" src="https://user-images.githubusercontent.com/55059449/83449051-3b28ec80-a453-11ea-93fd-552499924507.png">

**Comment by RabiRoshan** [comment] 2020-06-02 02:32
Hi @Milad-Akarie ,
Can you try with `firebase: ^7.3.0` package instead of `cloud_firestore: ^0.13.6` package.

I am using `auth()` and `firestore` from firebase.

Thank you.

**Comment by RabiRoshan** [comment] 2020-06-03 02:41
@Milad-Akarie Sorry... closed the issue by mistake 😅

**Comment by Milad-Akarie** [comment] 2020-07-19 19:49
Fixed injectable: 1.0.0 check it out!

**Closed by Milad-Akarie** 2020-07-19 19:49 UTC
