### ISSUE TITLE
[BUG] async factory results in Exception

### ISSUE THREAD

**Issue by DirtyNative** [Milad-Akarie/injectable#237] opened 2021-08-16 21:12 UTC
I created an async factory of a class:

```
@injectable
class AuthorizationRepository {

  AuthorizationRepository(anyParameter) {}

  @factoryMethod
  static Future<AuthorizationRepository> create(anyParameter) async {
    return new AuthorizationRepository(anyParameter);
  }
}
```

and after running build_runner and reloading the app I get the following error:

`You can't use get with an async Factory of AuthorizationRepository.
'package:get_it/get_it_impl.dart':
Failed assertion: line 399 pos 9: 'instanceFactory.factoryType == _ServiceFactoryType.constant ||
            instanceFactory.factoryType == _ServiceFactoryType.lazy'
`

I have also tried it with a module resulting in the same error. Related to #218

**Comment by Milad-Akarie** [comment] 2021-08-17 05:47
You Need to call `getIt.getAsync<AuthorizationRepository>()`
 instead of just `getIt.get<AuthorizationRepository>()`

**Comment by DirtyNative** [comment] 2021-08-17 07:50
I never call this by my own. I inject the `AuthorizationRepository` directly into. So this must then be a generator bug as it seems

**Comment by denis-shakinov-gismart** [comment] 2021-08-19 15:58
the problem is in code generating in 1.5.0
```
@module
abstract class AppModule {
  @preResolve
  Future<SharedPreferences> get sharedPreferences => SharedPreferences.getInstance();
```
here are whats generating in 1.4.1:
```
  final sharedPreferences = await appModule.sharedPreferences;  
  gh.factory<SharedPreferences>(() => sharedPreferences); 
```
and below it's injected anywhere with
`get<SharedPreferences>()`


now consider what's generating in version 1.5.0:
`await gh.factoryAsync<SharedPreferences>(() => appModule.sharedPreferences, preResolve: true);`
and below it's injected anywhere in factories with
`await get.getAsync<SharedPreferences>()`
and it automatically makes every instance registered as async, but it's not what we expected with `@preResolve` annotation

**Comment by proninyaroslav** [comment] 2021-08-21 18:35
@Milad-Akarie 
It broke some of my old dependencies that previously worked without `getAsync`

**Comment by proninyaroslav** [comment] 2021-08-21 18:47
@Milad-Akarie 
For example.
Before:
```Dart
gh.singletonWithDependencies<_i21.ServiceRepository>(
      () => _i21.ServiceRepositoryImpl(
          get<_i15.AppDatabase>(), get<_i14.ServiceAuthStorage>()),
      dependsOn: [_i15.AppDatabase]);
gh.factory<_i22.AccountsCubit>(
      () => _i22.AccountsCubit(get<_i21.ServiceRepository>()));
```
After:
```Dart
gh.singletonAsync<_i21.ServiceRepository>(
      () async => _i21.ServiceRepositoryImpl(
          await get.getAsync<_i15.AppDatabase>(),
          await get.getAsync<_i14.ServiceAuthStorage>()),
      dependsOn: [_i15.AppDatabase]);
gh.factoryAsync<_i22.AccountsCubit>(() async =>
      _i22.AccountsCubit(await get.getAsync<_i21.ServiceRepository>()));
```
In other words, if previously `singletonWithDependencies` were used, now `singletonAsync`, and all factories that depend on singletones have become async.

**Comment by proninyaroslav** [comment] 2021-08-23 16:36
@Milad-Akarie 
Please comment on this situation, is this the expected behavior in 1.5.0?

**Comment by Milad-Akarie** [comment] 2021-08-25 07:46
@proninyaroslav sorry for the delay, please downgrade until I fix this.

**Comment by Milad-Akarie** [comment] 2021-08-31 09:13
@proninyaroslav   This should be fixed in injectable_generator 1.5.1
please reopen if it's not.

**Closed** 2021-08-31 09:15 UTC

**Comment by proninyaroslav** [comment] 2021-09-08 18:21
@Milad-Akarie 
I upgraded to 1.5.2 and run `flutter pub run build_runner build --delete-conflicting-output`, but dependencies are still registered as async. Sorry for not checking this earlier.

**Comment by proninyaroslav** [comment] 2021-09-08 18:36
@Milad-Akarie
Here's the complete generated code:

<details>
<summary>Code</summary>

```Dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i8;
import 'package:get_it/get_it.dart' as _i1;
import 'package:http/http.dart' as _i5;
import 'package:injectable/injectable.dart' as _i2;
import 'package:shared_preferences/shared_preferences.dart' as _i18;

import 'core/app_database_isolate_binder.dart' as _i4;
import 'core/crash_report/crash_report_builder.dart' as _i31;
import 'core/crash_report/crash_report_id_generator.dart' as _i6;
import 'core/crash_report/crash_report_manager.dart' as _i52;
import 'core/crash_report/crash_report_sender.dart' as _i32;
import 'core/date_time_provider.dart' as _i7;
import 'core/model/fetcher.dart' as _i35;
import 'core/model/http/http_client.dart' as _i9;
import 'core/model/http/http_client_factory.dart' as _i10;
import 'core/model/parser_factory.dart' as _i12;
import 'core/model/request_factory.dart' as _i14;
import 'core/model/tracking_service.dart' as _i45;
import 'core/notification_manager.dart' as _i37;
import 'core/platform_info.dart' as _i13;
import 'core/settings/settings.dart' as _i30;
import 'core/storage/database.dart' as _i3;
import 'core/storage/service_auth_storage.dart' as _i16;
import 'core/storage/service_repository.dart' as _i17;
import 'core/storage/shipment_repository.dart' as _i19;
import 'core/storage/track_number_repository.dart' as _i20;
import 'core/storage/tracking_repository.dart' as _i22;
import 'core/storage/work_manager_repository.dart' as _i24;
import 'core/tracking_id_generator.dart' as _i21;
import 'core/tracking_limiter.dart' as _i43;
import 'core/tracking_scheduler.dart' as _i56;
import 'core/transaction_id_generator.dart' as _i23;
import 'core/work_manager/registered_workers.dart' as _i25;
import 'core/work_manager/work_manager.dart' as _i48;
import 'core/worker/tracking_all_worker.dart' as _i54;
import 'core/worker/tracking_notify_task.dart' as _i44;
import 'core/worker/tracking_periodic_worker.dart' as _i55;
import 'core/worker/tracking_task.dart' as _i46;
import 'core/worker/tracking_worker.dart' as _i47;
import 'core/worker/worker_manager.dart' as _i49;
import 'platform/system_tray.dart' as _i42;
import 'ui/about/about_cubit.dart' as _i26;
import 'ui/accounts/accounts_actions_cubit.dart' as _i27;
import 'ui/accounts/accounts_cubit.dart' as _i28;
import 'ui/add_account/add_account_cubit.dart' as _i29;
import 'ui/add_account/service_list_cubit.dart' as _i41;
import 'ui/add_parcels/add_parcels_cubit.dart' as _i57;
import 'ui/app_cubit.dart' as _i50;
import 'ui/cubit/error_report_cubit.dart' as _i53;
import 'ui/edit_account/edit_account_cubit.dart' as _i33;
import 'ui/edit_account/service_info_cubit.dart' as _i40;
import 'ui/parcel_details/details_actions_cubit.dart' as _i59;
import 'ui/parcel_details/edit_parcel_cubit.dart' as _i34;
import 'ui/parcel_details/parcel_details_cubit.dart' as _i38;
import 'ui/parcel_details/parcel_error_banner_cubit.dart' as _i11;
import 'ui/parcels/first_start_cubit.dart' as _i36;
import 'ui/parcels/parcels_actions_cubit.dart' as _i60;
import 'ui/parcels/parcels_cubit.dart' as _i39;
import 'ui/parcels/selectable_parcels_cubit.dart' as _i15;
import 'ui/settings/page/appearance_cubit.dart' as _i51;
import 'ui/settings/page/behavior_cubit.dart' as _i58;

const String _test = 'test';
const String _prod = 'prod';
const String _dev = 'dev';
// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
/// initializes the registration of provided dependencies inside of [GetIt]
_i1.GetIt $initGetIt(_i1.GetIt get,
    {String? environment, _i2.EnvironmentFilter? environmentFilter}) {
  final gh = _i2.GetItHelper(get, environment, environmentFilter);
  final appDatabaseModule = _$AppDatabaseModule();
  final clientModule = _$ClientModule();
  final flutterSecureStorageModule = _$FlutterSecureStorageModule();
  final sharedPreferencesModule = _$SharedPreferencesModule();
  gh.singletonAsync<_i3.AppDatabase>(() => appDatabaseModule.inMemoryDb,
      registerFor: {_test});
  gh.singletonAsync<_i3.AppDatabase>(() => appDatabaseModule.db,
      registerFor: {_prod, _dev});
  gh.singletonAsync<_i4.AppDatabaseIsolateBinder>(
      () async =>
          _i4.AppDatabaseIsolateBinder(await get.getAsync<_i3.AppDatabase>()),
      dependsOn: [_i3.AppDatabase]);
  gh.factory<_i5.Client>(() => clientModule.client);
  gh.factory<_i6.CrashReportIdGenerator>(
      () => _i6.CrashReportIdGeneratorImpl());
  gh.factory<_i7.DateTimeProvider>(() => _i7.DateTimeProviderImpl());
  gh.factory<_i8.FlutterSecureStorage>(
      () => flutterSecureStorageModule.testStorage,
      registerFor: {_test});
  gh.factory<_i8.FlutterSecureStorage>(() => flutterSecureStorageModule.storage,
      registerFor: {_prod, _dev});
  gh.factory<_i9.HttpClient>(() => _i9.HttpClientImpl(get<_i5.Client>()));
  gh.factory<_i10.HttpClientFactory>(
      () => _i10.HttpClientFactoryImpl(get<_i5.Client>()));
  gh.factory<_i11.ParcelErrorBannerCubit>(() => _i11.ParcelErrorBannerCubit());
  gh.factory<_i12.ParserFactory>(
      () => _i12.ParserFactoryImpl(get<_i7.DateTimeProvider>()));
  gh.factory<_i13.PlatformInfo>(() => _i13.PlatformInfoImpl());
  gh.factory<_i14.RequestFactory>(() => _i14.RequestFactoryImpl(),
      registerFor: {_prod});
  gh.factory<_i14.RequestFactory>(() => _i14.DevRequestFactoryImpl(),
      registerFor: {_dev, _test});
  gh.factory<_i15.SelectableParcelsCubit>(() => _i15.SelectableParcelsCubit());
  gh.factoryAsync<_i16.ServiceAuthStorage>(() async =>
      _i16.ServiceAuthStorageImpl(await get.getAsync<_i3.AppDatabase>(),
          get<_i8.FlutterSecureStorage>(), get<_i13.PlatformInfo>()));
  gh.singletonAsync<_i17.ServiceRepository>(
      () async => _i17.ServiceRepositoryImpl(
          await get.getAsync<_i3.AppDatabase>(),
          await get.getAsync<_i16.ServiceAuthStorage>()),
      dependsOn: [_i3.AppDatabase]);
  gh.singletonAsync<_i18.SharedPreferences>(() => sharedPreferencesModule.pref,
      registerFor: {_prod, _dev});
  gh.singletonAsync<_i18.SharedPreferences>(
      () => sharedPreferencesModule.testPref,
      registerFor: {_test});
  gh.singletonAsync<_i19.ShipmentRepository>(
      () async =>
          _i19.ShipmentRepositoryImpl(await get.getAsync<_i3.AppDatabase>()),
      dependsOn: [_i3.AppDatabase]);
  gh.singletonAsync<_i20.TrackNumberRepository>(
      () async =>
          _i20.TrackNumberRepositoryImpl(await get.getAsync<_i3.AppDatabase>()),
      dependsOn: [_i3.AppDatabase]);
  gh.factory<_i21.TrackingIdGenerator>(() => _i21.TrackingIdGeneratorImpl());
  gh.singletonAsync<_i22.TrackingRepository>(
      () async =>
          _i22.TrackingRepositoryImpl(await get.getAsync<_i3.AppDatabase>()),
      dependsOn: [_i3.AppDatabase]);
  gh.factory<_i23.TransactionIdGenerator>(
      () => _i23.TransactionIdGeneratorImpl());
  gh.singletonAsync<_i24.WorkManagerRepository>(
      () async =>
          _i24.WorkManagerRepositoryImpl(await get.getAsync<_i3.AppDatabase>()),
      dependsOn: [_i3.AppDatabase]);
  gh.factory<_i25.WorkersProvider>(() => _i25.WorkersProviderImpl());
  gh.factory<_i26.AboutCubit>(() => _i26.AboutCubit(get<_i13.PlatformInfo>()));
  gh.factoryAsync<_i27.AccountsActionsCubit>(() async =>
      _i27.AccountsActionsCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.factoryAsync<_i28.AccountsCubit>(() async =>
      _i28.AccountsCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.factoryAsync<_i29.AddAccountCubit>(() async =>
      _i29.AddAccountCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.singletonAsync<_i30.AppSettings>(
      () async =>
          _i30.AppSettingsImpl(await get.getAsync<_i18.SharedPreferences>()),
      dependsOn: [_i18.SharedPreferences]);
  gh.factory<_i31.CrashReportBuilder>(
      () => _i31.ProdCrashReportBuilder(
          get<_i13.PlatformInfo>(), get<_i6.CrashReportIdGenerator>()),
      registerFor: {_prod});
  gh.factory<_i31.CrashReportBuilder>(
      () => _i31.DevCrashReportBuilder(
          get<_i13.PlatformInfo>(), get<_i6.CrashReportIdGenerator>()),
      registerFor: {_dev});
  gh.factory<_i31.CrashReportBuilder>(
      () => _i31.TestCrashReportBuilder(
          get<_i13.PlatformInfo>(), get<_i6.CrashReportIdGenerator>()),
      registerFor: {_test});
  gh.factory<_i32.CrashReportSender>(
      () => _i32.CrashReportSenderImpl(get<_i13.PlatformInfo>()));
  gh.factoryAsync<_i33.EditAccountCubit>(() async =>
      _i33.EditAccountCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.factoryAsync<_i34.EditParcelCubit>(() async =>
      _i34.EditParcelCubit(await get.getAsync<_i20.TrackNumberRepository>()));
  gh.factory<_i35.Fetcher>(() => _i35.FetcherImpl(
      get<_i10.HttpClientFactory>(), get<_i7.DateTimeProvider>()));
  gh.factoryAsync<_i36.FirstStartCubit>(() async => _i36.FirstStartCubit(
      await get.getAsync<_i17.ServiceRepository>(),
      await get.getAsync<_i30.AppSettings>()));
  gh.singletonAsync<_i37.NotificationManager>(
      () async => _i37.NotificationManagerImpl(
          get<_i13.PlatformInfo>(), await get.getAsync<_i30.AppSettings>()),
      dependsOn: [_i30.AppSettings]);
  gh.factoryAsync<_i38.ParcelDetailsCubit>(() async => _i38.ParcelDetailsCubit(
      await get.getAsync<_i20.TrackNumberRepository>(),
      await get.getAsync<_i19.ShipmentRepository>(),
      await get.getAsync<_i22.TrackingRepository>()));
  gh.factoryAsync<_i39.ParcelsCubit>(() async => _i39.ParcelsCubit(
      await get.getAsync<_i20.TrackNumberRepository>(),
      await get.getAsync<_i22.TrackingRepository>(),
      await get.getAsync<_i19.ShipmentRepository>(),
      await get.getAsync<_i30.AppSettings>()));
  gh.factoryAsync<_i40.ServiceInfoCubit>(() async =>
      _i40.ServiceInfoCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.factoryAsync<_i41.ServiceListCubit>(() async =>
      _i41.ServiceListCubit(await get.getAsync<_i17.ServiceRepository>()));
  gh.factoryAsync<_i42.SystemTray>(() async => _i42.SystemTray(
      get<_i13.PlatformInfo>(), await get.getAsync<_i30.AppSettings>()));
  gh.factoryAsync<_i43.TrackingLimiter>(() async => _i43.TrackingLimiterImpl(
      await get.getAsync<_i30.AppSettings>(),
      await get.getAsync<_i22.TrackingRepository>(),
      get<_i7.DateTimeProvider>()));
  gh.factoryAsync<_i44.TrackingNotifyTask>(() async => _i44.TrackingNotifyTask(
      await get.getAsync<_i37.NotificationManager>(),
      await get.getAsync<_i20.TrackNumberRepository>(),
      await get.getAsync<_i30.AppSettings>()));
  gh.factory<_i45.TrackingService>(() => _i45.TrackingServiceImpl(
      get<_i14.RequestFactory>(),
      get<_i35.Fetcher>(),
      get<_i12.ParserFactory>()));
  gh.factoryAsync<_i46.TrackingTask>(() async => _i46.TrackingTask(
      trackingService: get<_i45.TrackingService>(),
      serviceRepo: await get.getAsync<_i17.ServiceRepository>(),
      shipmentRepo: await get.getAsync<_i19.ShipmentRepository>(),
      transactionIdGenerator: get<_i23.TransactionIdGenerator>(),
      trackingIdGenerator: get<_i21.TrackingIdGenerator>(),
      dateTimeProvider: get<_i7.DateTimeProvider>()));
  gh.factoryAsync<_i47.TrackingWorker>(() async => _i47.TrackingWorker(
      trackingTask: await get.getAsync<_i46.TrackingTask>(),
      trackNumberRepo: await get.getAsync<_i20.TrackNumberRepository>(),
      shipmentRepo: await get.getAsync<_i19.ShipmentRepository>(),
      trackingRepo: await get.getAsync<_i22.TrackingRepository>(),
      notifyTask: await get.getAsync<_i44.TrackingNotifyTask>(),
      platformInfo: get<_i13.PlatformInfo>(),
      pref: await get.getAsync<_i30.AppSettings>(),
      trackingLimiter: await get.getAsync<_i43.TrackingLimiter>()));
  gh.singletonAsync<_i48.WorkManager>(
      () async => _i48.DebugWorkManagerImpl(
          await get.getAsync<_i24.WorkManagerRepository>(),
          get<_i13.PlatformInfo>(),
          get<_i7.DateTimeProvider>(),
          get<_i25.WorkersProvider>()),
      dependsOn: [_i24.WorkManagerRepository],
      registerFor: {_dev, _test});
  gh.singletonAsync<_i48.WorkManager>(
      () async => _i48.WorkManagerImpl(
          await get.getAsync<_i24.WorkManagerRepository>(),
          get<_i13.PlatformInfo>(),
          get<_i25.WorkersProvider>(),
          get<_i7.DateTimeProvider>()),
      dependsOn: [_i24.WorkManagerRepository],
      registerFor: {_prod});
  gh.singletonAsync<_i49.WorkerManager>(
      () async =>
          _i49.WorkerManagerImpl(await get.getAsync<_i48.WorkManager>()),
      dependsOn: [_i48.WorkManager]);
  gh.singletonAsync<_i50.AppCubit>(
      () async => _i50.AppCubit(await get.getAsync<_i30.AppSettings>()),
      dependsOn: [_i30.AppSettings]);
  gh.factoryAsync<_i51.AppearanceSettingsCubit>(() async =>
      _i51.AppearanceSettingsCubit(
          await get.getAsync<_i30.AppSettings>(),
          await get.getAsync<_i50.AppCubit>(),
          await get.getAsync<_i42.SystemTray>()));
  gh.factory<_i52.CrashReportManager>(() => _i52.CrashReportManagerImpl(
      get<_i31.CrashReportBuilder>(), get<_i32.CrashReportSender>()));
  gh.factory<_i53.ErrorReportCubit>(
      () => _i53.ErrorReportCubit(get<_i52.CrashReportManager>()));
  gh.factoryAsync<_i54.TrackingAllWorker>(() async => _i54.TrackingAllWorker(
      await get.getAsync<_i47.TrackingWorker>(),
      await get.getAsync<_i20.TrackNumberRepository>(),
      get<_i13.PlatformInfo>(),
      await get.getAsync<_i30.AppSettings>()));
  gh.factoryAsync<_i55.TrackingPeriodicWorker>(() async =>
      _i55.TrackingPeriodicWorker(
          await get.getAsync<_i47.TrackingWorker>(),
          await get.getAsync<_i49.WorkerManager>(),
          await get.getAsync<_i22.TrackingRepository>(),
          await get.getAsync<_i20.TrackNumberRepository>(),
          await get.getAsync<_i30.AppSettings>(),
          get<_i13.PlatformInfo>(),
          get<_i7.DateTimeProvider>()));
  gh.singletonAsync<_i56.TrackingScheduler>(
      () async => _i56.TrackingSchedulerImpl(
          await get.getAsync<_i49.WorkerManager>(),
          await get.getAsync<_i20.TrackNumberRepository>(),
          await get.getAsync<_i43.TrackingLimiter>(),
          await get.getAsync<_i30.AppSettings>()),
      dependsOn: [_i49.WorkerManager]);
  gh.factoryAsync<_i57.AddParcelsCubit>(() async => _i57.AddParcelsCubit(
      await get.getAsync<_i20.TrackNumberRepository>(),
      await get.getAsync<_i56.TrackingScheduler>(),
      get<_i7.DateTimeProvider>()));
  gh.factoryAsync<_i58.BehaviorSettingsCubit>(() async =>
      _i58.BehaviorSettingsCubit(await get.getAsync<_i30.AppSettings>(),
          await get.getAsync<_i56.TrackingScheduler>()));
  gh.factoryAsync<_i59.DetailsActionsCubit>(() async =>
      _i59.DetailsActionsCubit(
          await get.getAsync<_i20.TrackNumberRepository>(),
          await get.getAsync<_i22.TrackingRepository>(),
          await get.getAsync<_i56.TrackingScheduler>()));
  gh.factoryAsync<_i60.ParcelsActionsCubit>(() async =>
      _i60.ParcelsActionsCubit(
          await get.getAsync<_i20.TrackNumberRepository>(),
          await get.getAsync<_i22.TrackingRepository>(),
          await get.getAsync<_i56.TrackingScheduler>()));
  return get;
}

class _$AppDatabaseModule extends _i3.AppDatabaseModule {}

class _$ClientModule extends _i9.ClientModule {}

class _$FlutterSecureStorageModule extends _i16.FlutterSecureStorageModule {}

class _$SharedPreferencesModule extends _i30.SharedPreferencesModule {}

```

</details>

**Comment by Milad-Akarie** [comment] 2021-09-09 09:59
@proninyaroslav Are you getting an error initializing this?  
in older versions registering a dependency that depends on an async dependency wouldn't work but not it should with the new changes. 
what section of code you think is generated incorrectly?

**Comment by proninyaroslav** [comment] 2021-09-09 10:17
@Milad-Akarie 
I'm getting absolutely the same errors. For example:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 399 pos 9: 'instanceFactory.factoryType == _ServiceFactoryType.constant ||
            instanceFactory.factoryType == _ServiceFactoryType.lazy': You can't use get with an async Factory of SystemTray.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _GetItImplementation.get
#3      _GetItImplementation.call
#4      _main
<asynchronous suspension>
```
Before 1.5.0 they worked without `getAsync`, but now they require it. Is this the expected behavior in 1.5.0? In this case, this isn't a minor change ([major].[minor].[patch] versioning), since it breaks the dependencies of current projects.

**Comment by Milad-Akarie** [comment] 2021-09-09 10:32
@proninyaroslav what 1.5.0 changed shouldn't been able to work before. 

if A which is non-async depends on B(async) then A becomes Async automatically in 1.5.0+ if it didn't resolving A should throw?

**Comment by proninyaroslav** [comment] 2021-09-09 15:14
@Milad-Akarie 
Previously, it generated `singletonWithDependencies` instead of `singletonAsync`, for example, this made it synchronous as it waited for asynchronous dependencies. Probably Injectable 2.0 would be a better idea instead of 1.5 (semantic versioning), as it breaks compatibility with current projects that were using 1.4, since I would have to change the `get` calls to `getAsync` and in change the logic of the code.

**Comment by proninyaroslav** [comment] 2021-09-12 09:33
For those who want to get the old behavior (generation of `singletonWithDependencies`): please use `@ preResolve` annotation for asynchronous dependencies.
